### PR TITLE
Logout button will now direct you back to the homepage if clicked

### PR DESCRIPTION
**Pull request by capi2002**
Created a JS file to add functionality to the logout button

### CODE REVIEW

**Comment by JakeyPooo** [comment]
Hey Luca, this .JS looks good, but it looks like it isn't integrated into classgpt.html file so the button actually isn't functional. Let's get that fixed so we can merge this.

**Comment by capi2002** [comment]
Should be good now! Please let me know if there are any other conflicts.

**Comment by JakeyPooo** [comment]
> 

We will need to retest this branch once we get completely integrated into Django. So once we merge Kevin's current PR, we will be good to retest this functionality.

**Comment by JakeyPooo** [comment]
Issue solved by other branch. Closing now.

**Pull request closed without merging**
